name: 'Setup Erg environment'
description: 'Setup a Erg environment by adding problem matchers and optionally downloading and adding it to the PATH'
author: 'Erg lang team'
inputs:
  erg-version:
    required: false
    default: '0.6.31'
    description: 'Version Spec of the version to use. Examples: 0.6.31'
  build:
    required: false
    default: 'stable'
    description: 'The build to use. Choices: stable, nightly'
runs:
  using: node16
  main: 'dist/index.js'
